[package]
name = "nrf52_components"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
components = { path = "../../components" }
cortexm4 = { path = "../../../arch/cortex-m4" }
capsules = { path = "../../../capsules" }
kernel = { path = "../../../kernel" }
nrf52 = { path = "../../../chips/nrf52" }
nrf52840-hal = { version = "0.10", features = ["rt"] }

[dependencies.rubble]
version = "0.0.3"
git = "https://github.com/daboross/rubble.git"
rev = "7677f92f0fc1a9d0f17977ada6eabd545086d26d"

[dependencies.rubble-nrf5x]
version = "0.0.3"
git = "https://github.com/daboross/rubble.git"
rev = "7677f92f0fc1a9d0f17977ada6eabd545086d26d"
features = ["52840"]
