[package]
name = "kernel"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
tock-registers = { path = "../libraries/tock-register-interface" }
tock-cells = { path = "../libraries/tock-cells" }

[dependencies.rubble]
version = "0.0.3"
git = "https://github.com/daboross/rubble.git"
rev = "7677f92f0fc1a9d0f17977ada6eabd545086d26d"
